# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.6.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.6.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/song/Code/GazeEstimation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/song/Code/GazeEstimation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.6.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.6.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/song/Code/GazeEstimation/CMakeFiles /Users/song/Code/GazeEstimation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/song/Code/GazeEstimation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EyeTracking

# Build rule for target.
EyeTracking: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EyeTracking
.PHONY : EyeTracking

# fast build rule for target.
EyeTracking/fast:
	$(MAKE) -f CMakeFiles/EyeTracking.dir/build.make CMakeFiles/EyeTracking.dir/build
.PHONY : EyeTracking/fast

source/ASDClassification.o: source/ASDClassification.cpp.o

.PHONY : source/ASDClassification.o

# target to build an object file
source/ASDClassification.cpp.o:
	$(MAKE) -f CMakeFiles/EyeTracking.dir/build.make CMakeFiles/EyeTracking.dir/source/ASDClassification.cpp.o
.PHONY : source/ASDClassification.cpp.o

source/ASDClassification.i: source/ASDClassification.cpp.i

.PHONY : source/ASDClassification.i

# target to preprocess a source file
source/ASDClassification.cpp.i:
	$(MAKE) -f CMakeFiles/EyeTracking.dir/build.make CMakeFiles/EyeTracking.dir/source/ASDClassification.cpp.i
.PHONY : source/ASDClassification.cpp.i

source/ASDClassification.s: source/ASDClassification.cpp.s

.PHONY : source/ASDClassification.s

# target to generate assembly for a file
source/ASDClassification.cpp.s:
	$(MAKE) -f CMakeFiles/EyeTracking.dir/build.make CMakeFiles/EyeTracking.dir/source/ASDClassification.cpp.s
.PHONY : source/ASDClassification.cpp.s

source/EyeTrackingData.o: source/EyeTrackingData.cpp.o

.PHONY : source/EyeTrackingData.o

# target to build an object file
source/EyeTrackingData.cpp.o:
	$(MAKE) -f CMakeFiles/EyeTracking.dir/build.make CMakeFiles/EyeTracking.dir/source/EyeTrackingData.cpp.o
.PHONY : source/EyeTrackingData.cpp.o

source/EyeTrackingData.i: source/EyeTrackingData.cpp.i

.PHONY : source/EyeTrackingData.i

# target to preprocess a source file
source/EyeTrackingData.cpp.i:
	$(MAKE) -f CMakeFiles/EyeTracking.dir/build.make CMakeFiles/EyeTracking.dir/source/EyeTrackingData.cpp.i
.PHONY : source/EyeTrackingData.cpp.i

source/EyeTrackingData.s: source/EyeTrackingData.cpp.s

.PHONY : source/EyeTrackingData.s

# target to generate assembly for a file
source/EyeTrackingData.cpp.s:
	$(MAKE) -f CMakeFiles/EyeTracking.dir/build.make CMakeFiles/EyeTracking.dir/source/EyeTrackingData.cpp.s
.PHONY : source/EyeTrackingData.cpp.s

source/Image.o: source/Image.cpp.o

.PHONY : source/Image.o

# target to build an object file
source/Image.cpp.o:
	$(MAKE) -f CMakeFiles/EyeTracking.dir/build.make CMakeFiles/EyeTracking.dir/source/Image.cpp.o
.PHONY : source/Image.cpp.o

source/Image.i: source/Image.cpp.i

.PHONY : source/Image.i

# target to preprocess a source file
source/Image.cpp.i:
	$(MAKE) -f CMakeFiles/EyeTracking.dir/build.make CMakeFiles/EyeTracking.dir/source/Image.cpp.i
.PHONY : source/Image.cpp.i

source/Image.s: source/Image.cpp.s

.PHONY : source/Image.s

# target to generate assembly for a file
source/Image.cpp.s:
	$(MAKE) -f CMakeFiles/EyeTracking.dir/build.make CMakeFiles/EyeTracking.dir/source/Image.cpp.s
.PHONY : source/Image.cpp.s

source/main.o: source/main.cpp.o

.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) -f CMakeFiles/EyeTracking.dir/build.make CMakeFiles/EyeTracking.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i

.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) -f CMakeFiles/EyeTracking.dir/build.make CMakeFiles/EyeTracking.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s

.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) -f CMakeFiles/EyeTracking.dir/build.make CMakeFiles/EyeTracking.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... EyeTracking"
	@echo "... source/ASDClassification.o"
	@echo "... source/ASDClassification.i"
	@echo "... source/ASDClassification.s"
	@echo "... source/EyeTrackingData.o"
	@echo "... source/EyeTrackingData.i"
	@echo "... source/EyeTrackingData.s"
	@echo "... source/Image.o"
	@echo "... source/Image.i"
	@echo "... source/Image.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

